### ISSUE TITLE
Understand the client access to reactive endpoints

### ISSUE THREAD

**Issue by mle-enso** [evainga/rememberbrall#11]
Study the following article: https://www.callicoder.com/reactive-rest-apis-spring-webflux-reactive-mongo/

…and answer the following questions:

Question 1: What are Server Sent Events?

Question 2: Try the following curl requests and answer: What is the fundamental difference between the following to requests to your Rememberbrall server:

- curl https://rememberbrall.herokuapp.com/entries -H "Accept: application/json"
- curl https://rememberbrall.herokuapp.com/entries -H "Accept: application/stream+json"

Question 3: Why is the second curl request above not appropriate for clients which rely on well-formed JSON data?

**Comment by evainga** [comment]
1:  SSE enable that clients can receive automatic updates from a server without the need of the browser/client to ask for updates
2: the first one gives back a JSON array with all the entries, the second one a stream with the separate JSON elements
3: because it doen't give back well formatted JSON data as there is for example no clear end of the JSON data...

**Comment by mle-enso** [comment]
Exactly – well done!
